// Change the draft id
@draftId =gv9mw-bb686
@requestId=7b0c9e48-2cb8-45fc-8672-d0ee5e2df3f5

// Dont push tokens from production !!!!
#@authToken = MCUTptsAkJbuSQtbh7U338y7Zp8MhiRkY9vvvhi3Cjte4r8zWVw6ZGsEghv0

// external token
@authToken = H2uYI83bmadSDK00pLQZ1Nuo6bTjoHAWCaOvgio4IK992uudSWj4MRzsCwwW

// Uncomment one related hostname
@hostname = https://127.0.0.1:5000
#@hostname = https://catalog.elter.cerit-sc.cz/
#@hostname = https://catalog.elter-ri.eu/

### Get draft info
GET {{hostname}}/api/lter/{{draftId}}/draft
Authorization: Bearer {{authToken}}

### Get requests of the draft
GET {{hostname}}/api/lter/{{draftId}}/draft/requests
Authorization: Bearer {{authToken}}

### Create EXT WORKFLOW request - start workflow
POST {{hostname}}/api/lter/{{draftId}}/draft/requests/run_external_workflow
Content-Type: application/json
Authorization: Bearer {{authToken}}

{}

### SUBMIT workflow request
POST {{hostname}}/api/requests/{{requestId}}/actions/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

### ACCEPT workflow request actions
POST {{hostname}}/api/requests/{{requestId}}/actions/accept
Authorization: Bearer {{authToken}}

### DECLINE workflow request actions
POST {{hostname}}/api/requests/{{requestId}}/actions/decline
Authorization: Bearer {{authToken}}