// Change the draft id
@draftId =438yy-dh815
@requestId=ddb61c29-d88c-41fd-a289-1671423c3f5a

// Dont push tokens from production !!!!
#@authToken = MCUTptsAkJbuSQtbh7U338y7Zp8MhiRkY9vvvhi3Cjte4r8zWVw6ZGsEghv0

// external token
@authToken = vuJz0InmgQ1wDedmrqushXXmGl4eJKnHdD2Z9dNBedEA16R9L8OYR5tgg8u3

// Uncomment one related hostname
@hostname = https://127.0.0.1:5000
#@hostname = https://catalog.elter.cerit-sc.cz/
#@hostname = https://catalog.elter-ri.eu/

### Get draft info
GET {{hostname}}/api/lter/{{draftId}}/draft
Authorization: Bearer {{authToken}}

### Get requests of the draft
GET {{hostname}}/api/lter/{{draftId}}/draft/requests
Authorization: Bearer {{authToken}}

### Create EXT WORKFLOW request - start workflow
POST {{hostname}}/api/lter/{{draftId}}/draft/requests/run_external_workflow
Content-Type: application/json
Authorization: Bearer {{authToken}}

{}

### SUBMIT workflow request
POST {{hostname}}/api/requests/{{requestId}}/actions/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

### ACCEPT workflow request actions
POST {{hostname}}/api/requests/{{requestId}}/actions/accept
Authorization: Bearer {{authToken}}

### DECLINE workflow request actions
POST {{hostname}}/api/requests/{{requestId}}/actions/decline
Authorization: Bearer {{authToken}}