@authToken = H2uYI83bmadSDK00pLQZ1Nuo6bTjoHAWCaOvgio4IK992uudSWj4MRzsCwwW
@recordId =gv9mw-bb686

// Uncomment one related hostname
#@hostname = https://127.0.0.1:5000
#@hostname = https://catalog.elter.cerit-sc.cz
@hostname = https://catalog.elter-ri.eu/

### GET All as XML
GET {{hostname}}/api/lter?size=500
Accept: text/xml

### GetRecord as XML
GET {{hostname}}/api/lter/{{recordId}}
Accept: text/xml

### GET All My records
GET {{hostname}}/api/user/lter
Authorization: Bearer {{authToken}}

### GET All My draft records
GET {{hostname}}//api/user/lter?not(state=draft)
Authorization: Bearer {{authToken}}

### Get All My actions
GET {{hostname}}/api/me
Authorization: Bearer {{authToken}}

### Get Community records
GET {{hostname}}/api/communities/deims

### Get Com records true
GET https://catalog.elter-ri.eu/api/communities/a301ac78-725a-41bc-bcb6-e914e564de17/records