GET https://catalog.elter-ri.eu/api/lter/?status=draft
#Accept: text/xml

###
GET https://catalog-invenio.elter-ri.eu/api/lter/0msdh-8cm33

###
GET https://catalog.elter-ri.eu/api/lter/?status=draft

###
GET https://catalog.elter-ri.eu/api/lter/draft

###
POST https://catalog.elter-ri.eu/api/lter/avnz1-h3n92/draft/actions/publish
Authorization: Bearer rSrs36mso8KW9qrGsbutdslpl7WOMhIktI1qVVr9DUuNPXpRZ6AXZpf4d2dG

###
POST https://catalog.elter-ri.eu/api/lter
Authorization: Bearer rSrs36mso8KW9qrGsbutdslpl7WOMhIktI1qVVr9DUuNPXpRZ6AXZpf4d2dG
Content-Type: application/json

{
  "metadata": {
    "datasetIds": [
      {
        "source": "b2share",
        "identifier": "id",
        "url": "url",
        "type": "PID"
      }
    ],
    "shortNames": [
      {
        "language": "eng",
        "text": "Test datataset with different keywords 2"
      }
    ],
    "titles": [
      {
        "language": "eng",
        "text": "Test datataset with different keywords 2"
      }
    ],
    "authors": [
      {
        "fullName": "Dominik MiddleName Dubovsky",
        "givenName": "Dominik",
        "familyName": "Dubovsky",
        "email": "user@example.com",
        "ids": [
          {
            "id": "12345",
            "schema": "Orcid",
            "url": "www.google.com"
          }
        ]
      }
    ],
    "contributors": [
      {
        "fullName": "Dominik MiddleName Dubovsky",
        "givenName": "Dominik",
        "familyName": "Dubovsky",
        "email": "user@example.com",
        "type": "MetadataProvider",
        "ids": [
          {
            "id": "12345",
            "schema": "Orcid",
            "url": "www.google.com"
          }
        ]
      }
    ],
    "publicationDate": "1999-02-24",
    "language": "english",
    "descriptions": [
      {
        "type": "Abstract",
        "language": "eng",
        "description": "This is a official abstract of the second dataset ingested into the Invenio Elter DAR component."
      },
      {
        "type": "AdditionalInfo",
        "language": "eng",
        "description": "This dataset is private, and is only for testing."
      }
    ],
    "keywords": [
      "Fruits", "Food"
    ],
    "propertyRights": [
      {
        "name": "name of the license",
        "url": "url of the license info"
      }
    ],
    "licenses": [
      {
        "name": "name of the license",
        "url": "url of the license"
      }
    ],
    "geoLocations": [
      {
        "description": "This is testing point location",
        "point": {
          "longitude": 10.50,
          "latitude": 10.50
        }
      },
      {
        "description": "This is testing box location",
        "box": {
          "westLongitude": 9.50,
          "eastLongitude": 10.50,
          "southLatitude": 9.50,
          "northLatitude": 10.50
        }
      }
    ],
    "temporalCoverages": [
      {
        "startDate": "1999-02-24",
        "endDate": "1999-02-24"
      }
    ],
    "taxonomicCoverages": [
      {
        "description": "description",
        "classification": {
          "id": "taxon_MAPY",
          "rankName": "species",
          "rankValue": "Macrocystis pyrifera",
          "commonName": "Giant Kelp"
        }
      }
    ],
    "methods": {
      "PID": "DOI - link to 'wiki - instruction manual",
      "steps": [
        {
          "title": "Title of the step",
          "description": "Description of the step"
        }
      ],
      "sampling": {
        "studyDescription": "Lorem ipsum.",
        "samplingDescription": "Lorem ipsum"
      },
      "qualityControlDescription": "Lorem ipsum.",
      "instrumentationDescription": "Lorem ipsum."
    },
    "project": {
      "name": "elter",
      "PID": "id of the project"
    },
    "siteReference": [
      {
        "name": "site name",
        "PID": "deims site id"
      }
    ],
    "SOReference": {
      "name": "",
      "url": "url"
    },
    "dataLevel": 2,
    "temporalResolution": 150,
    "ecosystem": {
      "name": "name",
      "PID": "PID"
    },
    "files": [
      {
        "md5": "checksum-hash",
        "format": "csv",
        "size": 234,
        "name": "File 1 - Testing file snapshot",
        "sourceUrl": "www.google.com"
      }
    ]
  }
}


###
GET https://127.0.0.1:5000/api/user/lter?q=metadata.shortName:Te???



#t3f71-mv568