from oarepo_runtime.services.search import I18nSearchOptions

from . import facets


class LterSearchOptions(I18nSearchOptions):
    """LterRecord search options."""

    facet_groups = {
        "default": {
            "state": facets.state,
            "metadata_dataLevel": facets.metadata_dataLevel,
            "metadata_keywords_name": facets.metadata_keywords_name,
            "metadata_datasetIds_sourceName": facets.metadata_datasetIds_sourceName,
            "metadata_siteReference_name": facets.metadata_siteReference_name,
            "metadata_SOReference_name": facets.metadata_SOReference_name,
            **getattr(I18nSearchOptions, "facet_groups", {}).get("default", {}),
        },
    }

    facets = {
        "externalWorkflow_defaultWorkflowTemplateId": facets.externalWorkflow_defaultWorkflowTemplateId,
        "externalWorkflow_history_date": facets.externalWorkflow_history_date,
        "externalWorkflow_history_status": facets.externalWorkflow_history_status,
        "externalWorkflow_history_workflowHandle": facets.externalWorkflow_history_workflowHandle,
        "externalWorkflow_history_workflowTemplateId": facets.externalWorkflow_history_workflowTemplateId,
        "metadata_SOReference_name": facets.metadata_SOReference_name,
        "metadata_SOReference_url": facets.metadata_SOReference_url,
        "metadata_additionalMetadata_name": facets.metadata_additionalMetadata_name,
        "metadata_assetType": facets.metadata_assetType,
        "metadata_authors_email": facets.metadata_authors_email,
        "metadata_authors_familyName": facets.metadata_authors_familyName,
        "metadata_authors_fullName": facets.metadata_authors_fullName,
        "metadata_authors_givenName": facets.metadata_authors_givenName,
        "metadata_authors_ids_id": facets.metadata_authors_ids_id,
        "metadata_authors_ids_schema": facets.metadata_authors_ids_schema,
        "metadata_authors_ids_url": facets.metadata_authors_ids_url,
        "metadata_contributors_email": facets.metadata_contributors_email,
        "metadata_contributors_familyName": facets.metadata_contributors_familyName,
        "metadata_contributors_fullName": facets.metadata_contributors_fullName,
        "metadata_contributors_givenName": facets.metadata_contributors_givenName,
        "metadata_contributors_ids_id": facets.metadata_contributors_ids_id,
        "metadata_contributors_ids_schema": facets.metadata_contributors_ids_schema,
        "metadata_contributors_ids_url": facets.metadata_contributors_ids_url,
        "metadata_contributors_type": facets.metadata_contributors_type,
        "metadata_dataLevel": facets.metadata_dataLevel,
        "metadata_datasetIds_identifier": facets.metadata_datasetIds_identifier,
        "metadata_datasetIds_sourceName": facets.metadata_datasetIds_sourceName,
        "metadata_datasetIds_type": facets.metadata_datasetIds_type,
        "metadata_datasetIds_url": facets.metadata_datasetIds_url,
        "metadata_descriptions_language": facets.metadata_descriptions_language,
        "metadata_descriptions_type": facets.metadata_descriptions_type,
        "metadata_ecosystem_PID": facets.metadata_ecosystem_PID,
        "metadata_ecosystem_name": facets.metadata_ecosystem_name,
        "metadata_files_format": facets.metadata_files_format,
        "metadata_files_md5": facets.metadata_files_md5,
        "metadata_files_name": facets.metadata_files_name,
        "metadata_files_size": facets.metadata_files_size,
        "metadata_files_sourceUrl": facets.metadata_files_sourceUrl,
        "metadata_geoLocations_EX_BoundingPolygon_inPolygonPoint_latitude": facets.metadata_geoLocations_EX_BoundingPolygon_inPolygonPoint_latitude,
        "metadata_geoLocations_EX_BoundingPolygon_inPolygonPoint_longitude": facets.metadata_geoLocations_EX_BoundingPolygon_inPolygonPoint_longitude,
        "metadata_geoLocations_EX_BoundingPolygon_points_latitude": facets.metadata_geoLocations_EX_BoundingPolygon_points_latitude,
        "metadata_geoLocations_EX_BoundingPolygon_points_longitude": facets.metadata_geoLocations_EX_BoundingPolygon_points_longitude,
        "metadata_geoLocations_EX_GeographicBoundingBox_eastBoundLongitude": facets.metadata_geoLocations_EX_GeographicBoundingBox_eastBoundLongitude,
        "metadata_geoLocations_EX_GeographicBoundingBox_northBoundLatitude": facets.metadata_geoLocations_EX_GeographicBoundingBox_northBoundLatitude,
        "metadata_geoLocations_EX_GeographicBoundingBox_southBoundLatitude": facets.metadata_geoLocations_EX_GeographicBoundingBox_southBoundLatitude,
        "metadata_geoLocations_EX_GeographicBoundingBox_westBoundLongitude": facets.metadata_geoLocations_EX_GeographicBoundingBox_westBoundLongitude,
        "metadata_geoLocations_Point_latitude": facets.metadata_geoLocations_Point_latitude,
        "metadata_geoLocations_Point_longitude": facets.metadata_geoLocations_Point_longitude,
        "metadata_geoServerInfo_mapData_bytetype": facets.metadata_geoServerInfo_mapData_bytetype,
        "metadata_geoServerInfo_mapData_epsgCode": facets.metadata_geoServerInfo_mapData_epsgCode,
        "metadata_geoServerInfo_mapData_features_label": facets.metadata_geoServerInfo_mapData_features_label,
        "metadata_geoServerInfo_mapData_features_name": facets.metadata_geoServerInfo_mapData_features_name,
        "metadata_geoServerInfo_mapData_features_style_colour": facets.metadata_geoServerInfo_mapData_features_style_colour,
        "metadata_geoServerInfo_mapData_path": facets.metadata_geoServerInfo_mapData_path,
        "metadata_geoServerInfo_mapData_type": facets.metadata_geoServerInfo_mapData_type,
        "metadata_geoServerInfo_serviceType": facets.metadata_geoServerInfo_serviceType,
        "metadata_keywords_name": facets.metadata_keywords_name,
        "metadata_keywords_url": facets.metadata_keywords_url,
        "metadata_language": facets.metadata_language,
        "metadata_licenses_name": facets.metadata_licenses_name,
        "metadata_licenses_url": facets.metadata_licenses_url,
        "metadata_methods_PID": facets.metadata_methods_PID,
        "metadata_methods_steps_title": facets.metadata_methods_steps_title,
        "metadata_project_DOI": facets.metadata_project_DOI,
        "metadata_project_PID": facets.metadata_project_PID,
        "metadata_project_name": facets.metadata_project_name,
        "metadata_propertyRights_name": facets.metadata_propertyRights_name,
        "metadata_propertyRights_url": facets.metadata_propertyRights_url,
        "metadata_publicationDate": facets.metadata_publicationDate,
        "metadata_shortNames_language": facets.metadata_shortNames_language,
        "metadata_siteReference_PID": facets.metadata_siteReference_PID,
        "metadata_siteReference_name": facets.metadata_siteReference_name,
        "metadata_taxonomicCoverages_classification_commonName": facets.metadata_taxonomicCoverages_classification_commonName,
        "metadata_taxonomicCoverages_classification_id": facets.metadata_taxonomicCoverages_classification_id,
        "metadata_taxonomicCoverages_classification_rankName": facets.metadata_taxonomicCoverages_classification_rankName,
        "metadata_taxonomicCoverages_classification_rankValue": facets.metadata_taxonomicCoverages_classification_rankValue,
        "metadata_temporalCoverages_endDate": facets.metadata_temporalCoverages_endDate,
        "metadata_temporalCoverages_startDate": facets.metadata_temporalCoverages_startDate,
        "metadata_temporalResolution": facets.metadata_temporalResolution,
        "metadata_titles_language": facets.metadata_titles_language,
        "metadata_version": facets.metadata_version,
        "state": facets.state,
        **getattr(I18nSearchOptions, "facets", {}),
        "record_status": facets.record_status,
        "has_draft": facets.has_draft,
    }
