from invenio_records_resources.services import SearchOptions as InvenioSearchOptions

from . import facets


class LterSearchOptions(InvenioSearchOptions):
    """LterRecord search options."""

    facet_groups = {}

    facets = {
        "metadata_contributors_affiliation_affiliationIdentifier": facets.metadata_contributors_affiliation_affiliationIdentifier,
        "metadata_contributors_affiliation_affiliationIdentifierScheme": facets.metadata_contributors_affiliation_affiliationIdentifierScheme,
        "metadata_contributors_affiliation_name": facets.metadata_contributors_affiliation_name,
        "metadata_contributors_affiliation_schemeURI": facets.metadata_contributors_affiliation_schemeURI,
        "metadata_contributors_contributorType": facets.metadata_contributors_contributorType,
        "metadata_contributors_familyName": facets.metadata_contributors_familyName,
        "metadata_contributors_givenName": facets.metadata_contributors_givenName,
        "metadata_contributors_lang": facets.metadata_contributors_lang,
        "metadata_contributors_name": facets.metadata_contributors_name,
        "metadata_contributors_nameIdentifiers_nameIdentifier": facets.metadata_contributors_nameIdentifiers_nameIdentifier,
        "metadata_contributors_nameIdentifiers_nameIdentifierScheme": facets.metadata_contributors_nameIdentifiers_nameIdentifierScheme,
        "metadata_contributors_nameIdentifiers_schemeURI": facets.metadata_contributors_nameIdentifiers_schemeURI,
        "metadata_contributors_nameType": facets.metadata_contributors_nameType,
        "metadata_creators_affiliation_affiliationIdentifier": facets.metadata_creators_affiliation_affiliationIdentifier,
        "metadata_creators_affiliation_affiliationIdentifierScheme": facets.metadata_creators_affiliation_affiliationIdentifierScheme,
        "metadata_creators_affiliation_name": facets.metadata_creators_affiliation_name,
        "metadata_creators_affiliation_schemeURI": facets.metadata_creators_affiliation_schemeURI,
        "metadata_creators_familyName": facets.metadata_creators_familyName,
        "metadata_creators_givenName": facets.metadata_creators_givenName,
        "metadata_creators_lang": facets.metadata_creators_lang,
        "metadata_creators_name": facets.metadata_creators_name,
        "metadata_creators_nameIdentifiers_nameIdentifier": facets.metadata_creators_nameIdentifiers_nameIdentifier,
        "metadata_creators_nameIdentifiers_nameIdentifierScheme": facets.metadata_creators_nameIdentifiers_nameIdentifierScheme,
        "metadata_creators_nameIdentifiers_schemeURI": facets.metadata_creators_nameIdentifiers_schemeURI,
        "metadata_creators_nameType": facets.metadata_creators_nameType,
        "metadata_descriptions_descriptionType": facets.metadata_descriptions_descriptionType,
        "metadata_descriptions_lang": facets.metadata_descriptions_lang,
        "metadata_doi": facets.metadata_doi,
        "metadata_geoLocations_geoLocationBox_eastBoundLongitude": facets.metadata_geoLocations_geoLocationBox_eastBoundLongitude,
        "metadata_geoLocations_geoLocationBox_northBoundLatitude": facets.metadata_geoLocations_geoLocationBox_northBoundLatitude,
        "metadata_geoLocations_geoLocationBox_southBoundLatitude": facets.metadata_geoLocations_geoLocationBox_southBoundLatitude,
        "metadata_geoLocations_geoLocationBox_westBoundLongitude": facets.metadata_geoLocations_geoLocationBox_westBoundLongitude,
        "metadata_geoLocations_geoLocationPlace": facets.metadata_geoLocations_geoLocationPlace,
        "metadata_geoLocations_geoLocationPoint_pointLatitude": facets.metadata_geoLocations_geoLocationPoint_pointLatitude,
        "metadata_geoLocations_geoLocationPoint_pointLongitude": facets.metadata_geoLocations_geoLocationPoint_pointLongitude,
        "metadata_geoLocations_geoLocationPolygons_inPolygonPoint_pointLatitude": facets.metadata_geoLocations_geoLocationPolygons_inPolygonPoint_pointLatitude,
        "metadata_geoLocations_geoLocationPolygons_inPolygonPoint_pointLongitude": facets.metadata_geoLocations_geoLocationPolygons_inPolygonPoint_pointLongitude,
        "metadata_geoLocations_geoLocationPolygons_polygonPoints_pointLatitude": facets.metadata_geoLocations_geoLocationPolygons_polygonPoints_pointLatitude,
        "metadata_geoLocations_geoLocationPolygons_polygonPoints_pointLongitude": facets.metadata_geoLocations_geoLocationPolygons_polygonPoints_pointLongitude,
        "metadata_identifiers_relatedIdentifier": facets.metadata_identifiers_relatedIdentifier,
        "metadata_identifiers_relatedIdentifierType": facets.metadata_identifiers_relatedIdentifierType,
        "metadata_identifiers_relatedMetadataScheme": facets.metadata_identifiers_relatedMetadataScheme,
        "metadata_identifiers_relationType": facets.metadata_identifiers_relationType,
        "metadata_identifiers_resourceTypeGeneral": facets.metadata_identifiers_resourceTypeGeneral,
        "metadata_identifiers_schemeType": facets.metadata_identifiers_schemeType,
        "metadata_identifiers_schemeURI": facets.metadata_identifiers_schemeURI,
        "metadata_keywords": facets.metadata_keywords,
        "metadata_language": facets.metadata_language,
        "metadata_project": facets.metadata_project,
        "metadata_publicationYear": facets.metadata_publicationYear,
        "metadata_resourceTypes_resourceType": facets.metadata_resourceTypes_resourceType,
        "metadata_resourceTypes_resourceTypeGeneral": facets.metadata_resourceTypes_resourceTypeGeneral,
        "metadata_rightsList_lang": facets.metadata_rightsList_lang,
        "metadata_rightsList_rights": facets.metadata_rightsList_rights,
        "metadata_rightsList_rightsIdentifier": facets.metadata_rightsList_rightsIdentifier,
        "metadata_rightsList_rightsIdentifierScheme": facets.metadata_rightsList_rightsIdentifierScheme,
        "metadata_rightsList_rightsURI": facets.metadata_rightsList_rightsURI,
        "metadata_rightsList_schemeURI": facets.metadata_rightsList_schemeURI,
        "metadata_shortName": facets.metadata_shortName,
        "metadata_taxanomicCoverages_classificationCode": facets.metadata_taxanomicCoverages_classificationCode,
        "metadata_taxanomicCoverages_lang": facets.metadata_taxanomicCoverages_lang,
        "metadata_taxanomicCoverages_schemeURI": facets.metadata_taxanomicCoverages_schemeURI,
        "metadata_taxanomicCoverages_subject": facets.metadata_taxanomicCoverages_subject,
        "metadata_taxanomicCoverages_subjectScheme": facets.metadata_taxanomicCoverages_subjectScheme,
        "metadata_taxanomicCoverages_valueURI": facets.metadata_taxanomicCoverages_valueURI,
        "metadata_temporalCoverages_date": facets.metadata_temporalCoverages_date,
        "metadata_temporalCoverages_dateInformation": facets.metadata_temporalCoverages_dateInformation,
        "metadata_temporalCoverages_dateType": facets.metadata_temporalCoverages_dateType,
        **getattr(InvenioSearchOptions, "facets", {}),
        "record_status": facets.record_status,
        "has_draft": facets.has_draft,
    }
